services:
  jekyll:
    build: .
    image: jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: ["bundle","exec","jekyll","serve","-H","0.0.0.0","-w","--config","_config.yml,_config_docker.yml"]